"""Video tutorials — manifest + media serving (v62.5).
MP4s are pre-generated by /app/scripts/generate_tutorials.py (real app
screenshots + AI voiceover) into backend/static/tutorials/."""
import json
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse

from auth import get_current_user

router = APIRouter(prefix="/tutorials", tags=["tutorials"])

MEDIA_DIR = Path(__file__).resolve().parents[1] / "static" / "tutorials"


@router.get("/manifest")
async def tutorials_manifest(user=Depends(get_current_user)):
    mf = MEDIA_DIR / "manifest.json"
    if not mf.exists():
        return {"tutorials": [], "note": "no tutorials generated yet"}
    return json.loads(mf.read_text())


@router.get("/media/{name}")
async def tutorial_media(name: str, user=Depends(get_current_user)):
    if "/" in name or ".." in name or not name.endswith(".mp4"):
        raise HTTPException(status_code=400, detail="bad media name")
    f = MEDIA_DIR / name
    if not f.exists():
        raise HTTPException(status_code=404, detail="not found")
    return FileResponse(f, media_type="video/mp4",
                        headers={"Cache-Control": "public, max-age=86400"})
