#!/usr/bin/env bash
# STOIC one-command install — builds and starts the full stack (API + 6
# workers + Mongo + frontend [+ TLS ingress]) with generated secrets.
# Idempotent. A deployment MODE is required — no accidental public deploys:
#   deploy/install.sh --dev                     local/dev (loopback-only ports)
#   deploy/install.sh --production <domain>     public TLS deployment via Caddy
#   … --with-forecast                           OPT-IN Chronos/GBM forecast
#                                               profile (≥16 GB RAM hosts)
set -euo pipefail
cd "$(dirname "$0")/.."

WITH_FORECAST=0
REGISTRY=0
ARGS=()
for a in "$@"; do
  case "$a" in
    --with-forecast) WITH_FORECAST=1 ;;
    --registry) REGISTRY=1 ;;
    *) ARGS+=("$a") ;;
  esac
done
MODE="${ARGS[0]:-}"
DOMAIN="${ARGS[1]:-}"
case "${MODE}" in
  --dev) ;;
  --production)
    [ -n "${DOMAIN}" ] || { echo "ERROR: --production requires a domain: deploy/install.sh --production trade.example.com"; exit 1; }
    ;;
  *)
    echo "ERROR: deployment mode is required (prevents accidental public deployment"
    echo "       in development configuration):"
    echo "         deploy/install.sh --dev"
    echo "         deploy/install.sh --production <domain>"
    exit 1
    ;;
esac

echo "== STOIC installer (${MODE#--}${DOMAIN:+ · $DOMAIN}) =="

command -v docker >/dev/null || { echo "ERROR: docker is required"; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "ERROR: docker compose v2 is required"; exit 1; }

gen() { python3 -c "import secrets;print(secrets.token_urlsafe(32))"; }

# The installer is SELF-CONTAINED: if the .env.example templates are missing
# from the archive, equivalent templates are written inline so a fresh
# deployment never fails on a packaging gap.
ensure_root_template() {
  [ -f .env.example ] && return
  echo "   (writing missing .env.example inline)"
  cat > .env.example <<'EOF'
# Compose-level config — copy to ./.env (repo root). deploy/install.sh
# fills this automatically. NON-SECRET values only: passwords/keys live in
# Docker secrets under ./secrets/ (also generated by install.sh).
MONGO_ROOT_USER=
MONGO_APP_USER=
DB_NAME=
REACT_APP_BACKEND_URL=
EOF
}

ensure_backend_template() {
  [ -f backend/.env.example ] && return
  echo "   (writing missing backend/.env.example inline)"
  cat > backend/.env.example <<'EOF'
# STOIC backend environment — copy to backend/.env and fill in.
MONGO_URL=
DB_NAME=
CORS_ORIGINS=
FRED_API_KEY=
JWT_SECRET=
ADMIN_EMAIL=
ADMIN_PASSWORD=
EMERGENT_LLM_KEY=
ALPHA_VANTAGE_KEY=
NEWSAPI_KEY=
FINNHUB_KEY=
BOT_LOOP_INTERVAL_SEC=
BOT_SIGNAL_COOLDOWN_MIN=
MACRO_FREEZE_BEFORE_MIN=
MACRO_FREEZE_AFTER_MIN=
STRIPE_API_KEY=
BINANCE_LIVE_ENABLED=
CRYPTO_MAX_RISK_PCT_PER_TRADE=
RESEND_API_KEY=
SENDER_EMAIL=
RATE_LIMIT_EXEMPT_IPS=
RATE_LIMIT_BYPASS_TOKEN=
STEP_UP_BYPASS_TOKEN=
KEY_VAULT_MASTER=
BACKGROUND_WORKERS_IN_PROCESS=
METRICS_TOKEN=
WS_ALLOW_QUERY_TOKEN=
EOF
}

set_kv() {  # set_kv <file> <key> <value> — idempotent set-or-append
  if grep -q "^$2=" "$1"; then
    sed -i.bak "s|^$2=.*|$2=$3|" "$1" && rm -f "$1.bak"
  else
    printf '%s=%s\n' "$2" "$3" >> "$1"
  fi
}

# 0 · Docker secrets — all credentials live here, never in .env files
if [ ! -d secrets ]; then
  echo "-- generating Docker secrets in ./secrets/"
  mkdir -p secrets && chmod 700 secrets
  DB_NAME_VAL=ai_trading_bot
  APP_PWD=$(gen)
  gen > secrets/mongo_root_password
  printf '%s' "${APP_PWD}" > secrets/mongo_app_password
  printf 'mongodb://stoic_app:%s@mongo:27017/%s?authSource=%s' \
    "${APP_PWD}" "${DB_NAME_VAL}" "${DB_NAME_VAL}" > secrets/mongo_url
  gen > secrets/jwt_secret
  gen > secrets/key_vault_master
  gen > secrets/metrics_token
  chmod 600 secrets/*
  echo "   generated mongo_root_password, mongo_app_password, mongo_url,"
  echo "   jwt_secret, key_vault_master, metrics_token (mode 600)."
else
  echo "-- ./secrets exists — leaving untouched"
fi

# 1 · compose-level .env — NON-SECRET config only
if [ ! -f .env ]; then
  echo "-- creating ./.env (compose config)"
  ensure_root_template
  cp .env.example .env
fi
set_kv .env MONGO_ROOT_USER stoic_root
set_kv .env MONGO_APP_USER stoic_app
set_kv .env DB_NAME ai_trading_bot
if [ "${MODE}" = "--production" ]; then
  set_kv .env DOMAIN "${DOMAIN}"
  set_kv .env REACT_APP_BACKEND_URL ""      # same-origin behind the TLS ingress
  set_kv .env COMPOSE_FILE "docker-compose.yml:docker-compose.tls.yml"
else
  set_kv .env COMPOSE_FILE "docker-compose.yml"
fi
if [ "${WITH_FORECAST}" = "1" ]; then
  echo "-- forecast profile ENABLED (torch CPU + Chronos-Bolt; ~+1.5 GB image)"
  CF=$(grep '^COMPOSE_FILE=' .env | cut -d= -f2-)
  case ":${CF}:" in
    *:docker-compose.forecast.yml:*) ;;
    *) set_kv .env COMPOSE_FILE "${CF}:docker-compose.forecast.yml" ;;
  esac
  set_kv .env ML_FORECAST 1
fi
if [ "${REGISTRY}" = "1" ]; then
  echo "-- deploy mode: REGISTRY (pull CI-built GHCR images by attested digest — no local build)"
  set_kv .env DEPLOY_MODE registry
fi

# 2 · backend/.env — non-secret config (credentials arrive via Docker secrets)
if [ ! -f backend/.env ]; then
  echo "-- creating backend/.env"
  ensure_backend_template
  cp backend/.env.example backend/.env
  set_kv backend/.env DB_NAME ai_trading_bot
  set_kv backend/.env ADMIN_EMAIL admin@stoic.local
  set_kv backend/.env ADMIN_PASSWORD "$(gen)"
  set_kv backend/.env BOT_LOOP_INTERVAL_SEC 30
  set_kv backend/.env BOT_SIGNAL_COOLDOWN_MIN 30
  set_kv backend/.env MACRO_FREEZE_BEFORE_MIN 30
  set_kv backend/.env MACRO_FREEZE_AFTER_MIN 15
  set_kv backend/.env BINANCE_LIVE_ENABLED false
  set_kv backend/.env CRYPTO_MAX_RISK_PCT_PER_TRADE 1.0
  set_kv backend/.env WS_ALLOW_QUERY_TOKEN false
  echo "   seed admin: admin@stoic.local (password in backend/.env — change after first login)"
  echo "   review backend/.env for integration keys (LLM, news, email) before go-live."
else
  echo "-- backend/.env exists — leaving untouched"
fi

# 3 · deployment-mode hardening (explicit, not just a warning)
if [ "${MODE}" = "--production" ]; then
  set_kv backend/.env APP_ENV production
  set_kv backend/.env CSRF_ENFORCE_ORIGIN true
  set_kv backend/.env CORS_ORIGINS "https://${DOMAIN},https://www.${DOMAIN}"
else
  grep -q "^APP_ENV=production" backend/.env && {
    echo "ERROR: backend/.env says APP_ENV=production but you ran --dev."
    echo "       Re-run with: deploy/install.sh --production <domain>"; exit 1; }
  set_kv backend/.env APP_ENV development
  echo "   DEV MODE: all ports bound to 127.0.0.1 only — not publicly reachable."
fi

# 4 · build + start
echo "-- building images"
# Immutable Git + image provenance (deploy/lib.sh) — the backend image build
# HARD-FAILS without the commit SHA; production boot requires the digest.
. deploy/lib.sh
if [ "${MODE}" = "--production" ]; then
  # First production install: the checkout must be a signed, attested release.
  # Override consciously with ATTESTATION_REQUIRED=false in ./.env (not advised).
  verify_attestation || { echo "ERROR: release attestation gate failed — refusing production install"; exit 1; }
fi
if [ "$(deploy_mode)" = "registry" ] && [ "${MODE}" != "--production" ]; then
  # registry mode is digest-driven: the attestation is the ONLY source of the digests
  verify_attestation || { echo "ERROR: release attestation gate failed — registry mode cannot resolve images"; exit 1; }
fi
provision_images || exit 1
echo "-- starting stack"
compose_up

# 5 · full release-readiness verification — an install that cannot prove the
#     complete trading topology (HTTPS/frontend, Mongo round trip, all six
#     workers, loop progress, reconciliation, outbox, schema) DOES NOT count
#     as complete.
echo "-- waiting for API health"
for i in $(seq 1 45); do
  if curl -fsS http://127.0.0.1:8001/api/health >/dev/null 2>&1; then
    echo "   API is up"
    break
  fi
  [ "$i" = 45 ] && { echo "ERROR: API did not become healthy"; docker compose logs backend | tail -30; exit 1; }
  sleep 2
done

echo "-- verifying full release readiness (Mongo, 6 workers, loop progress, reconciliation, outbox, schema)"
METRICS_TOKEN=$(cat secrets/metrics_token)
READY=0
for i in $(seq 1 60); do   # workers need time to acquire leases + first loop iterations
  if curl -fsS -H "X-Metrics-Token: ${METRICS_TOKEN}" \
       http://127.0.0.1:8001/api/ops/release-readiness >/dev/null 2>&1; then
    READY=1; break
  fi
  sleep 4
done
if [ "${READY}" != 1 ]; then
  echo "ERROR: release-readiness never became ready — final state:"
  curl -sS -H "X-Metrics-Token: ${METRICS_TOKEN}" \
    http://127.0.0.1:8001/api/ops/release-readiness || true
  echo ""
  docker compose logs --tail 25
  echo "INSTALL INCOMPLETE — the stack is running but NOT verified. Fix the"
  echo "failing checks above and re-run the installer."
  exit 1
fi
echo "   release-readiness: ready"

if [ "${MODE}" = "--production" ]; then
  echo "-- verifying HTTPS end-to-end (Caddy certificate for ${DOMAIN})"
  TLS_OK=0
  for i in $(seq 1 36); do   # cert issuance can take ~1-2 min after DNS resolves
    if curl -fsS "https://${DOMAIN}/api/health" >/dev/null 2>&1; then
      TLS_OK=1; break
    fi
    sleep 5
  done
  if [ "${TLS_OK}" != 1 ]; then
    echo "ERROR: https://${DOMAIN}/api/health is not reachable with a valid certificate."
    echo "       Check that DNS points at this host and ports 80/443 are open,"
    echo "       then re-run: deploy/install.sh --production ${DOMAIN}"
    docker compose logs caddy --tail 20 || true
    exit 1
  fi
  echo "   HTTPS verified"
else
  echo "-- verifying frontend"
  curl -fsS -o /dev/null http://127.0.0.1:3000 || { echo "ERROR: frontend not reachable on 127.0.0.1:3000"; exit 1; }
  echo "   frontend serving"
fi

echo "-- worker status"
docker compose ps --format '{{.Name}}\t{{.Status}}' | grep worker || true

if [ "${WITH_FORECAST}" = "1" ]; then
  echo "-- verifying forecast profile (loads Chronos-Bolt once; model is cached in the hf_cache volume)"
  if docker compose exec -T worker-trading python ops/verify_forecast_profile.py; then
    echo "   forecast plane READY in worker-trading"
  else
    echo "ERROR: forecast profile verification failed — see output above"; exit 1
  fi
fi

echo ""
echo "== install complete =="
if [ "${MODE}" = "--production" ]; then
  echo "   app:   https://${DOMAIN}  (Caddy provisions the certificate on first request)"
else
  echo "   app:   http://127.0.0.1:3000   (loopback only)"
fi
echo "   next:  deploy/backup.sh schedule · deploy/soak.sh start · docs/DEPLOYMENT.md"
