"""Fixed solution / verify text per check (reviewed; an AI may rephrase what_happened only)."""

PLAYBOOKS = {
    "A1": ("Password brute force", "If the password is weak or reused the attacker gets the account — for an admin, every account.",
           ["Confirm the account password is unique and 16+ characters.", "Confirm MFA is on for every admin.",
            "Optional: enable the Turnstile challenge after 5 failures."], "No new A1 findings for this target in 24 h."),
    "A2": ("2FA / OTP guessing", "A guessed 6-digit code bypasses the second factor.",
           ["Confirm the OTP lockout (5 failures / 10 min) is active.", "Ask the user to rotate their password and re-enrol MFA."],
           "No new A2 findings for this account in 24 h."),
    "A3": ("Credential stuffing", "Leaked password lists are being replayed against many accounts.",
           ["Block the source IP/range at Cloudflare.", "Force a password reset for the accounts that failed."], "Failure counts per IP back to baseline."),
    "A4": ("Refresh-token reuse (stolen session)", "A copied refresh token means the session was stolen.",
           ["The family is revoked automatically; the user must log in again with MFA.", "Ask the user to check their devices."], "No further reuse events for the user."),
    "A5": ("New-country login after failures", "A successful login right after failures from a new place looks like a takeover.",
           ["Confirm with the user; revoke their sessions if unknown.", "Enforce MFA for the user."], "User confirms the login."),
    "A6": ("Admin action without step-up", "An admin write happened without a fresh second factor — the control is bypassed or broken.",
           ["Find the route in admin_audit_log and add require_step_up.", "Revoke the actor's sessions until explained."], "No new A6 events; the route asks for step-up."),
    "A7": ("401/403/429 spike", "Scanning or brute force against the API.",
           ["Review the top IPs/paths in the evidence.", "Block at Cloudflare if one source dominates."], "Rate back to baseline."),
    "B1": ("Bridge token used from two places", "Two terminals share one token — one of them is not yours.",
           ["Rotate the bridge token (Accounts → Rotate token) and re-pair the real EA.", "Check the VPS for unknown terminals."],
           "Heartbeats come from one IP/terminal only."),
    "B2": ("Bridge token guessing", "Someone is probing the EA bridge with invalid tokens.",
           ["Block the IP at Cloudflare.", "Keep BRIDGE_IP_LIMIT_PER_MIN at or below 1200."], "No invalid-token requests from that IP for 1 h."),
    "B3": ("Order without valid authorisation", "An order or setting change bypassed the signed authorisation chain.",
           ["Freeze new entries on the account until explained (admin).", "Inspect order_authorizations for the nonce in the evidence."], "No new B3 events."),
    "S1": ("Secret pattern in logs", "Secrets in logs leak through log shipping, backups and screenshots.",
           ["Find the log line from the evidence (masked) and remove the value from the log call.", "Rotate the secret if it was printed in clear anywhere."],
           "S1 counters stay at zero for 24 h."),
    "S2": ("Weak secret / debug flag / wildcard CORS", "Weak secrets or debug settings make every other control weaker.",
           ["Set the variable named in the evidence to a strong value (32+ random chars) in Docker secrets.", "Set CORS_ORIGINS explicitly."],
           "S2 re-check passes at the next hourly run."),
    "S3": ("TLS certificate expiring", "An expired certificate takes the platform and the EA bridge offline.",
           ["Renew the certificate (Cloudflare / cPanel AutoSSL).", "Confirm auto-renewal is on."], "Expiry > 14 days."),
    "S4": ("Database or backend port public", "A reachable Mongo/backend port means direct data access from the internet.",
           ["Close the port in the host firewall; only Cloudflare → nginx should be reachable.", "Rotate DB credentials if it was open."], "Port probe refused."),
    "S5": ("Security headers missing", "Missing HSTS/CSP/X-Frame-Options enable downgrade and clickjacking attacks.",
           ["Compare server.py security headers with the response; check the proxy does not strip them."], "All headers present on the public URL."),
    "D1": ("Python package CVE", "A known vulnerability in a dependency is a ready-made exploit.",
           ["Upgrade the package to the fixed version in requirements.txt (pip freeze after install).", "If no fix exists, document the exposure."], "pip-audit clean."),
    "D2": ("Frontend package CVE", "Vulnerable frontend packages expose users' browsers.",
           ["Run yarn upgrade for the package and audit-ci in CI."], "audit-ci passes."),
    "I1": ("Duplicate open tickets", "Two live rows for one broker ticket double-count exposure and P&L.",
           ["Run ops/ticket_duplicates.py (dry run), resolve MANUAL groups, then --archive --yes."], "duplicate_tickets() returns no groups."),
    "I2": ("Required unique index missing", "Without the unique index the same ticket/deal/user can be inserted twice.",
           ["Run ops/ticket_duplicates.py --build-index after resolving duplicates; restart the API."], "Index present in the next check."),
    "I3": ("Audit chain broken", "A broken hash chain means audit records were altered or lost.",
           ["Do not repair silently: export admin_audit_log, find the first bad seq, investigate who wrote after it."], "verify_chain ok=true."),
    "I4": ("Backup stale or restore failed", "Without a fresh, restorable backup an incident becomes data loss.",
           ["Check deploy/backup cron and disk space; run update.sh (it dumps Mongo).", "Run the restore test."], "Backup younger than 26 h."),
    "P1": ("Worker lease / crash loop", "A dead worker means protection, reconciliation or trading loops are not running.",
           ["docker compose ps; restart the worker named in the evidence; read its log."], "Lease fresh, loops running."),
    "P2": ("SLO breach (5xx / latency)", "Users and the EA see errors or slow responses.",
           ["Check /api/ops/runtime-stats and the backend log for the failing route."], "Error budget recovering."),
    "P3": ("Event loop blocked / crash", "A blocked loop stalls every request and heartbeat.",
           ["Read runtime_crash_log; find the blocking call in the evidence stack."], "No blockage in 1 h."),
    "P4": ("Disk / RAM pressure", "A full disk stops Mongo and logging; RAM pressure gets processes killed.",
           ["Prune old backups/logs (deploy/update.sh keeps the last dumps); check docker system df."], "Usage below threshold."),
    "P5": ("Repeated exception group", "The same error 20+ times means a loop is failing silently.",
           ["Open the component/where in the evidence; fix the root cause; add a test."], "Counter stops growing."),
    "T1": ("EA heartbeats stale platform-wide", "Many terminals silent at once points to a server/network outage, not one VPS.",
           ["Check the bridge endpoint from outside, Cloudflare status and the backend log."], "Heartbeats fresh on most accounts."),
    "T2": ("Orders unacked / unprotected / reconcile stuck", "Positions without confirmation or stop protection are unmanaged risk.",
           ["Check the EA on the account; the protection guard escalates to FULL_CLOSE after 90 s unprotected."], "ops_alerts cleared."),
    "agent_check_failed": ("A security check failed to run", "A silent check is a blind spot.",
                           ["Read the traceback in the evidence; fix the check."], "The check runs clean."),
}


def playbook(check_id: str) -> dict:
    t, why, sol, ver = PLAYBOOKS.get(check_id) or PLAYBOOKS["agent_check_failed"]
    return {"title": t, "why_it_matters": why, "solution": sol, "verify": ver}
