#!/usr/bin/env python3
"""Generate docs/TEST_MANIFEST.md — a formal classification of every test.

Classes:
  unit         backend/tests/unit/**            no I/O beyond in-memory
  integration  backend/tests/integration/**     real MongoDB service
  http-live    backend/tests/test_*.py (root)   live API server + DB
  ui-e2e       e2e/tests/*.spec.ts              real browser (Playwright)

CI regenerates this file and fails on drift, so the manifest can never lie.
Usage: python scripts/generate_test_manifest.py [--check]
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "TEST_MANIFEST.md"

PY_TEST_RE = re.compile(r"^\s*(?:async\s+)?def\s+test_\w+", re.M)
TS_TEST_RE = re.compile(r"^\s*(?:test|setup)\(", re.M)


def classify(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    if rel.startswith("e2e/"):
        return "ui-e2e"
    if "/tests/unit/" in rel:
        return "unit"
    if "/tests/integration/" in rel:
        return "integration"
    return "http-live"


def count_tests(path: Path) -> int:
    text = path.read_text(errors="ignore")
    rx = TS_TEST_RE if path.suffix == ".ts" else PY_TEST_RE
    return len(rx.findall(text))


def main() -> int:
    files = sorted(
        [*(ROOT / "backend" / "tests").rglob("test_*.py"),
         *(ROOT / "e2e" / "tests").glob("*.ts")],
        key=lambda p: (classify(p), p.as_posix()))
    rows, totals = [], {}
    for f in files:
        cls = classify(f)
        n = count_tests(f)
        totals[cls] = totals.get(cls, 0) + n
        rows.append(f"| `{f.relative_to(ROOT).as_posix()}` | {cls} | {n} |")

    lines = [
        "# Test Manifest",
        "",
        "Formal classification of every test in the repository. Generated by",
        "`scripts/generate_test_manifest.py` — **do not edit by hand**; CI",
        "fails when this file drifts from the tree.",
        "",
        "| class | meaning | runs in | count |",
        "|-------|---------|---------|-------|",
        f"| unit | pure logic, no external I/O | every CI job | {totals.get('unit', 0)} |",
        f"| integration | real MongoDB service container | CI `backend-integration` | {totals.get('integration', 0)} |",
        f"| http-live | live API server + database | staging/soak (`scripts/run_full_suite.sh`) | {totals.get('http-live', 0)} |",
        f"| ui-e2e | real browser via Playwright | CI `frontend-e2e` | {totals.get('ui-e2e', 0)} |",
        "",
        f"**Total: {sum(totals.values())} tests across {len(files)} files.**",
        "",
        "| file | class | tests |",
        "|------|-------|-------|",
        *rows,
        "",
    ]
    content = "\n".join(lines)
    if "--check" in sys.argv:
        if OUT.read_text() != content:
            print("TEST_MANIFEST.md is stale — run "
                  "scripts/generate_test_manifest.py and commit.")
            return 1
        print("TEST_MANIFEST.md is up to date.")
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT} ({sum(totals.values())} tests, {len(files)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
