"""iter-171 (#9) — DB index manifest generator.

Connects to MongoDB and writes a manifest of every collection's indexes to
docs/INDEX_MANIFEST.md. Run in CI (or locally) after changing indexes so the
committed manifest tracks the real index topology; a drift check can diff the
live indexes against the committed manifest.
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), "..", "backend", ".env"))

OUT = os.path.join(os.path.dirname(__file__), "..", "docs", "INDEX_MANIFEST.md")


def _key_str(key) -> str:
    return ", ".join(f"{k}:{v}" for k, v in key.items())


async def main():
    from motor.motor_asyncio import AsyncIOMotorClient
    db = AsyncIOMotorClient(os.environ["MONGO_URL"])[os.environ["DB_NAME"]]
    names = sorted(await db.list_collection_names())
    lines = ["# MongoDB Index Manifest",
             "",
             "_Auto-generated by `scripts/generate_index_manifest.py`. "
             "Do not edit by hand._",
             "",
             f"Collections: {len(names)}",
             ""]
    total = 0
    for c in names:
        idx = await db[c].index_information()
        lines.append(f"## `{c}` ({len(idx)} indexes)")
        for name, spec in sorted(idx.items()):
            key = dict(spec.get("key", []))
            flags = []
            if spec.get("unique"):
                flags.append("unique")
            if spec.get("expireAfterSeconds") is not None:
                flags.append(f"ttl={spec['expireAfterSeconds']}s")
            if spec.get("sparse"):
                flags.append("sparse")
            suffix = f" [{', '.join(flags)}]" if flags else ""
            lines.append(f"- `{name}`: {{{_key_str(key)}}}{suffix}")
            total += 1
        lines.append("")
    lines.insert(5, f"Total indexes: {total}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} ({total} indexes across {len(names)} collections)")


if __name__ == "__main__":
    asyncio.run(main())
